/**
 * Copyright (c) 2016 Chiral Behaviors, LLC, all rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.chiralbehaviors.inviscid.measure;

import java.util.ArrayList;
import java.util.List;

import javax.vecmath.Point3i;

import com.chiralbehaviors.inviscid.QuantaField;
import com.chiralbehaviors.inviscid.lga.FccNeighborhood;

/**
 * The dynamic structure factor S(k,omega) of the coarse-grained quanta
 * (frequency) field: a spatial transform over the even-parity sublattice
 * followed by a temporal transform, so emergent collective branches
 * (bead inviscid-0nx, design memo "Measurement layer" section) present as
 * ridges in the (k,omega) plane instead of a hope.
 *
 * <h2>The sublattice is FCC, not simple cubic - reciprocal-lattice
 * reasoning (the subtle core of this class)</h2>
 * {@code Necronomata}'s state lives only on the even-parity sublattice
 * {@code {(i,j,k) in Z^3 : i+j+k even}} of the cubic index space (see
 * {@code Necronomata#forEach} / {@code FccNeighborhood}'s class javadoc).
 * In the conventional-cell description standard in solid-state physics,
 * this set is exactly a face-centered-cubic (FCC) Bravais lattice: it is
 * generated by the three vectors {@code (1,1,0)}, {@code (1,0,1)},
 * {@code (0,1,1)} and has index 2 in {@code Z^3} (the determinant of that
 * generator matrix is {@code -2}). A naive full-cubic FFT that zero-fills
 * the empty odd-parity sites (option (a) considered and rejected for this
 * class) multiplies the true field by the indicator {@code c(r) = (1 +
 * exp(i*pi*(i+j+k)))/2}, i.e. by a constant plus a single plane wave at
 * {@code G0 = pi*(1,1,1)} - convolving the true spectrum with a copy of
 * itself shifted by {@code G0}, a deterministic ghost image, not noise.
 *
 * <p><b>The approach taken here (a variant of option (b)/(c)): a direct
 * DFT that sums explicitly and ONLY over the even-parity sites.</b> No
 * odd-parity site is ever read, let alone zero-filled, so this class
 * structurally cannot exhibit option (a)'s zero-comb ghost - there is no
 * artificial data for a ghost to be convolved from. What direct summation
 * over the sublattice DOES exhibit is the sublattice's own, GENUINE
 * reciprocal-space periodicity: the FCC direct lattice's reciprocal
 * lattice is the standard dual BCC lattice, consisting of every vector
 * {@code G} whose three components are integer multiples of {@code pi}
 * with equal parity (all even or all odd) integer coefficients. For any
 * such {@code G} and any field on the sublattice, {@code F(k+G) == F(k)}
 * EXACTLY - not an approximation, not an artifact of this implementation,
 * but a per-term algebraic identity: {@code exp(-i*(k+G)*r) ==
 * exp(-i*k*r) * exp(-i*G*r)}, and {@code exp(-i*G*r) == 1} for every
 * {@code r} on the sublattice by {@code G}'s own defining condition.
 *
 * <p>On the discrete grid this class actually evaluates -
 * {@code k = 2*pi*(mx/Ex, my/Ey, mz/Ez)} for the box's periodic extents,
 * all even per {@link FccNeighborhood}'s precondition - the only such
 * coincidence reachable within one full period per axis is
 * {@code G0 = pi*(1,1,1)}, i.e. simultaneously shifting
 * {@code (mx,my,mz)} by {@code (Ex/2, Ey/2, Ez/2)}. Its consequence is
 * direction-dependent:
 * <ul>
 * <li><b>[100] and [110] probes.</b> {@code G0}'s shift always introduces
 * a nonzero component on an axis the probe holds fixed at zero (a [100]
 * probe fixes {@code my=mz=0}; {@code G0} needs both nonzero to reach the
 * partner). The ghost partner therefore always leaves the probed
 * ray/plane and is never itself reported by that probe - the full,
 * un-restricted {@code m} range {@code [0, extent)} can be reported with
 * no internal duplication.</li>
 * <li><b>[111] probe.</b> {@code G0}'s shift ({@code t -> t+pi} on every
 * component simultaneously) maps the {@code [111]} ray back onto itself,
 * so the SAME probe, if left unrestricted, would report both
 * {@code F(k)} and its exact duplicate {@code F(k+G0)} as if they were
 * independent data. This class restricts the reported {@code [111]}
 * range to the first half, {@code m in [0, extent/2)}, discarding the
 * provably redundant (not merely presumed redundant, not distorted)
 * other half - see {@code StructureFactorTest#evenParitySublatticeIndexingIsCorrect}
 * for a test that directly compares the retained and discarded halves
 * and asserts they are numerically identical.</li>
 * </ul>
 *
 * <h2>Spatial transform: direct DFT, not the radix-2 {@link Fft}</h2>
 * {@link Fft} requires a power-of-two length; legal FCC extents (even,
 * &gt;=4 per {@link FccNeighborhood}) include non-power-of-two values
 * such as 6. Spatial extents in this domain are tiny (4..8ish), so an
 * {@code O(N)}-per-k direct summation (an {@code O(N^2)} DFT over the
 * whole axis) is trivially cheap and removes the power-of-two
 * constraint entirely - the RECOMMENDED choice over requiring
 * power-of-two spatial extents. The TEMPORAL axis has no such
 * constraint (it is a simulation-tick count, not a lattice extent), so
 * it reuses {@link Fft}'s existing radix-2 transform directly; {@code T}
 * (the snapshot count) must be a power of two.
 *
 * <h2>What field is transformed</h2>
 * {@link #coarseGrainedField(QuantaField)} coarse-grains a substrate's
 * 30-slots-per-cell quanta (5 cubes x 6 members, see
 * {@code Necronomata}'s class javadoc for the layout this seam's
 * contract pins) down to one scalar per even-parity cell: the sum of
 * that cell's 30 member quanta, read via {@link QuantaField#quantaAt(int)}
 * (the same substrate-agnostic seam {@code ConservationAudit} uses).
 * This is always real-valued - the public API only ever accepts a real
 * field.
 *
 * @author halhildebrand
 */
public final class StructureFactor {

    /**
     * Probe direction, in the conventional-cubic-cell index frame (the
     * same frame {@code Necronomata}'s {@code (i,j,k)} addresses).
     */
    public enum Direction {
        X100, X110, X111
    }

    /**
     * One ridge point: at spatial index {@code m}, the SIGNED scalar
     * {@code k}, {@code sqrt(Nd)} times the SIGNED (folded) per-axis
     * reciprocal-space component ({@code Nd} = 1/2/3 equal nonzero
     * components for X100/X110/X111) - {@code m > axisExtent/2} is a
     * negative-k alias, matching {@code SpectrumAnalyzer}'s established
     * upper-half-is-negative convention, and {@code k} is NOT folded to
     * a non-negative magnitude.
     *
     * <p>Two DELIBERATE, review-verified design points, both bead
     * inviscid-0nx.9 stacked review:
     * <ul>
     * <li><b>{@code sqrt(Nd)} scaling (round 1, critic).</b> Reporting
     * the bare per-axis component for X110/X111 would make
     * {@link Ridge#slope()} incomparable across directions - a
     * perfectly isotropic dispersion {@code omega = c*|k|} would
     * misreport as slopes {@code c}, {@code c*sqrt(2)},
     * {@code c*sqrt(3)}, a spurious ~41%/~73% "anisotropy" that is a
     * pure reporting-convention artifact, not physics (see
     * {@code StructureFactorTest#isotropicDispersionGivesConsistentSlopeAcrossDirections}).</li>
     * <li><b>{@code k} is SIGNED, never {@code abs()}-folded (round 2,
     * critic).</b> A real-valued field's spatial DFT is Hermitian -
     * {@code F(-k,t) == conj(F(k,t))} for real {@code f} - so a real
     * single-direction propagating wave's mirror index
     * ({@code axisExtent-m}) lands at exactly {@code -k} with exactly
     * {@code -omega}: the SAME dispersion line. Folding {@code k} to a
     * non-negative magnitude would make that mirror collide with the
     * forward point at an IDENTICAL {@code k} but OPPOSITE-sign
     * {@code omega}, which CANCELS (not reinforces) in
     * {@link #extractRidge}'s unweighted OLS fit over the raw,
     * unfiltered {@link #spectrum} output - exactly what a real caller
     * (bead .10) does. See
     * {@code StructureFactorTest#realFieldRidgeReinforcesAcrossMirrorPointsX100}
     * (and {@code ...X110}), which fail by ~34% slope corruption
     * against an {@code abs()}-folded {@code k}.</li>
     * </ul>
     * The dominant temporal frequency is {@code omega} and its
     * {@code power}; {@code peakFraction} is that power as a fraction of
     * the total power summed over every omega bin at this k.
     */
    public record DispersionPoint(int m, double k, double omega,
                                   double power, double peakFraction) {
    }

    /**
     * A fitted dispersion branch: the ridge points it was fit from, plus
     * ordinary-least-squares {@code slope} (domega/dk, a group-velocity
     * estimate) and {@code intercept}.
     */
    public record Ridge(List<DispersionPoint> points, double slope,
                         double intercept) {
        public Ridge {
            points = List.copyOf(points);
        }
    }

    /**
     * One full-shell grid point: the raw 3-index grid coordinate
     * {@code (mx, my, mz)} (unrestricted on {@code my}/{@code mz}, but
     * always {@code mx < extent.x/2} - see {@link #fullShell}'s
     * canonicalization rule), its Euclidean magnitude {@code k}, and the
     * dominant temporal frequency/power/peakFraction exactly as
     * {@link DispersionPoint} reports them for a single probe direction.
     */
    public record ShellPoint(int mx, int my, int mz, double k, double omega,
                              double power, double peakFraction) {
    }

    private final Point3i extent;

    /**
     * @param extent the periodic-wrap extent; delegated to
     *               {@link FccNeighborhood}'s constructor for validation
     *               (reused, not re-implemented) - every axis must be
     *               positive, even, and at least 4.
     * @throws IllegalArgumentException under the same conditions as
     *                                  {@link FccNeighborhood#FccNeighborhood(Point3i)}.
     */
    public StructureFactor(Point3i extent) {
        new FccNeighborhood(extent);
        this.extent = new Point3i(extent);
    }

    /**
     * @return a defensive copy of the periodic-wrap extent.
     */
    public Point3i getExtent() {
        return new Point3i(extent);
    }

    /**
     * Coarse-grains {@code automaton}'s current quanta field to one
     * scalar per even-parity cell: the sum of that cell's 30 member
     * quanta. Read-only - uses {@link QuantaField#quantaAt(int)}
     * strictly, per that method's contract, exactly like
     * {@code ConservationAudit} does. Substrate-agnostic (bead
     * inviscid-ckn / inviscid-0nx.21): identical for every
     * {@link QuantaField} implementation, not {@code Necronomata}-specific.
     *
     * @return a {@code double[]} of length
     *         {@code extent.x*extent.y*extent.z}, addressed via
     *         {@code (i*extent.y+j)*extent.z+k} (mirroring
     *         {@link QuantaField#indexOfCell(Point3i)}'s convention,
     *         without the {@code *30} member stride). Slots at
     *         odd-parity indices are left at {@code 0.0} and are never
     *         read by {@link #spectrum(double[][], Direction)} - this is
     *         bookkeeping convenience, not the option-(a) zero-fill
     *         failure mode described in the class javadoc, since the
     *         transform never sums over them.
     */
    public static double[] coarseGrainedField(QuantaField automaton) {
        Point3i ext = automaton.extent();
        double[] field = new double[ext.x * ext.y * ext.z];
        automaton.forEachCell(cell -> {
            int base = automaton.indexOfCell(cell);
            double sum = 0;
            for (int m = 0; m < 30; m++) {
                sum += automaton.quantaAt(base + m);
            }
            int idx = (cell.x * ext.y + cell.y) * ext.z + cell.z;
            field[idx] = sum;
        });
        return field;
    }

    /**
     * The dynamic structure factor's dominant ridge along {@code
     * direction}, for a real-valued field time series. One
     * {@link DispersionPoint} per probed {@code m}; see the class
     * javadoc for which {@code m} range each {@code direction} reports
     * and why.
     *
     * @param fieldByTick {@code fieldByTick[t]} is a snapshot in the
     *                    {@link #coarseGrainedField(QuantaField)}
     *                    layout; {@code fieldByTick.length} (T) must be
     *                    a power of two (temporal {@link Fft}
     *                    requirement).
     */
    public List<DispersionPoint> spectrum(double[][] fieldByTick,
                                           Direction direction) {
        return spectrum(fieldByTick, null, direction);
    }

    /**
     * Package-private complex-field overload. The physical production
     * field is always real ({@link #coarseGrainedField(QuantaField)});
     * this overload exists solely so tests can inject an exact complex
     * plane-wave oracle ({@code exp(i*(k.x - omega*t))}) without the
     * mirror-image power splitting a real {@code cos}/{@code sin} series
     * would introduce - see {@code StructureFactorTest}'s
     * {@code planeWaveGivesSingleKOmegaPeak} javadoc, which mirrors
     * {@code SpectrumAnalyzer}'s identical, already-locked precedent.
     *
     * @param fieldIm nullable; {@code null} means a purely real field
     *                (equivalent to an all-zero imaginary array).
     */
    List<DispersionPoint> spectrum(double[][] fieldRe, double[][] fieldIm,
                                    Direction direction) {
        requireFieldShape(fieldRe, fieldIm);
        int axisExtent = axisExtentFor(direction);
        int mMax = direction == Direction.X111 ? axisExtent / 2
                                                : axisExtent;
        int t = fieldRe.length;
        List<DispersionPoint> points = new ArrayList<>(mMax);
        for (int m = 0; m < mMax; m++) {
            int[] idx = kIndicesFor(direction, m);
            double[] power = powerSpectrumAt(fieldRe, fieldIm, idx[0],
                                              idx[1], idx[2]);
            double total = 0;
            int peakP = 0;
            for (int p = 0; p < t; p++) {
                total += power[p];
                if (power[p] > power[peakP]) {
                    peakP = p;
                }
            }
            double omega = signedOmega(peakP, t);
            double k = Math.sqrt(componentCountFor(direction))
                       * kComponentMagnitude(m, axisExtent);
            double peakFraction = total > 0 ? power[peakP] / total : 0.0;
            points.add(new DispersionPoint(m, k, omega, power[peakP],
                                            peakFraction));
        }
        return points;
    }

    /**
     * The raw temporal power spectrum {@code S(omega)} at one specific,
     * unrestricted grid point {@code (mx, my, mz)} - the public,
     * real-field promotion of the internal {@link #powerSpectrumAt}
     * building block (bead inviscid-0nx.9 stacked review, Important 3):
     * lets a caller inspect an arbitrary grid point directly rather than
     * only the points a {@link Direction} probe visits. {@link #fullShell}
     * is the enumerator built on top of this for scanning many points at
     * once.
     */
    public double[] spectrumAt(double[][] fieldByTick, int mx, int my,
                                int mz) {
        requireFieldShape(fieldByTick, null);
        return powerSpectrumAt(fieldByTick, null, mx, my, mz);
    }

    /**
     * The "full-shell option" the bead's Deliverable names: every grid
     * point {@code (mx, my, mz)} whose SIGNED-index Euclidean magnitude
     * ({@code sqrt(sx^2+sy^2+sz^2)} over the folded/signed per-axis
     * indices) is at most {@code mMagnitudeMax}, with the
     * reciprocal-lattice ghost pairs described in the class javadoc
     * deduplicated to exactly one representative each.
     *
     * <h2>Canonicalization rule</h2>
     * The ghost identity is {@code F(k+G0) == F(k)} for
     * {@code G0 = pi*(1,1,1)}, i.e. simultaneously shifting
     * {@code (mx,my,mz)} by {@code (extent.x/2, extent.y/2, extent.z/2)}
     * (mod extent, componentwise). That shift ALWAYS moves {@code mx}
     * from the first half of its range {@code [0, extent.x/2)} to the
     * second half {@code [extent.x/2, extent.x)}, or vice versa (since
     * {@code extent.x} is even and the shift is exactly half of it) -
     * so restricting the enumeration to {@code mx in [0, extent.x/2)}
     * (full range on {@code my}/{@code mz}) keeps EXACTLY one point from
     * every {@code {k, k+G0}} pair, for every triple, not merely the
     * [111] diagonal the per-direction {@link #spectrum} restriction
     * handles. This generalizes that same restriction; the choice of
     * {@code mx} (rather than {@code my} or {@code mz}) as the
     * restricted axis is arbitrary but fixed.
     *
     * <p><b>Caveat for real-field callers fitting slopes (recorded,
     * non-blocking, bead inviscid-0nx.9 stacked review round 2):</b> the
     * {@code mx}-canonicalization above dedups only the reciprocal-lattice
     * ghost ({@code G0}); it does NOT dedup the SEPARATE real-field
     * Hermitian-mirror pair ({@code k} and {@code -k}, see
     * {@link DispersionPoint}'s javadoc) on the {@code mx=0} slice, where
     * both a point and its Hermitian mirror can appear as distinct
     * {@code ShellPoint}s. A caller fitting an OLS ridge directly against
     * {@link #fullShell} output for a REAL field must account for that
     * mirror pairing itself (e.g. restrict to a half-space, or rely on the
     * mirror pair reinforcing rather than canceling - it does, since
     * {@code ShellPoint.k} is likewise unfolded/signed - see
     * {@code StructureFactorTest#realFieldRidgeReinforcesAcrossMirrorPointsX100}).
     * Bead .10 uses the named {@link Direction} probes, not this method,
     * and is unaffected.
     */
    public List<ShellPoint> fullShell(double[][] fieldByTick,
                                       int mMagnitudeMax) {
        requireFieldShape(fieldByTick, null);
        List<ShellPoint> shell = new ArrayList<>();
        int t = fieldByTick.length;
        for (int mx = 0; mx < extent.x / 2; mx++) {
            for (int my = 0; my < extent.y; my++) {
                for (int mz = 0; mz < extent.z; mz++) {
                    double kx = signedIndex(mx, extent.x) * 2 * Math.PI
                                / extent.x;
                    double ky = signedIndex(my, extent.y) * 2 * Math.PI
                                / extent.y;
                    double kz = signedIndex(mz, extent.z) * 2 * Math.PI
                                / extent.z;
                    double sx = signedIndex(mx, extent.x);
                    double sy = signedIndex(my, extent.y);
                    double sz = signedIndex(mz, extent.z);
                    double indexMagnitude = Math.sqrt(sx * sx + sy * sy
                                                        + sz * sz);
                    if (indexMagnitude > mMagnitudeMax) {
                        continue;
                    }
                    double[] power = powerSpectrumAt(fieldByTick, null, mx,
                                                       my, mz);
                    double total = 0;
                    int peakP = 0;
                    for (int p = 0; p < t; p++) {
                        total += power[p];
                        if (power[p] > power[peakP]) {
                            peakP = p;
                        }
                    }
                    double omega = signedOmega(peakP, t);
                    double kMag = Math.sqrt(kx * kx + ky * ky + kz * kz);
                    double peakFraction = total > 0 ? power[peakP] / total
                                                     : 0.0;
                    shell.add(new ShellPoint(mx, my, mz, kMag, omega,
                                              power[peakP], peakFraction));
                }
            }
        }
        return shell;
    }

    /**
     * The raw temporal power spectrum {@code S(omega)} (length T, one
     * value per temporal FFT bin, see {@link #signedOmega(int, int)} for
     * the bin-to-signed-omega convention) at one specific, unrestricted
     * {@code (mx, my, mz)} grid point - the building block
     * {@link #spectrum(double[][], double[][], Direction)} iterates over
     * per probe direction, and also the tool
     * {@code StructureFactorTest#evenParitySublatticeIndexingIsCorrect}
     * uses directly to verify the reciprocal-lattice ghost-partner
     * identity described in the class javadoc.
     *
     * <p><b>Why {@link Fft#ifft(double[], double[])}, not
     * {@link Fft#fft(double[], double[])}, for the temporal axis.</b>
     * The standard spacetime-transform sign convention pairs a {@code
     * -i*k*x} spatial exponent (what {@link #spatialDft} computes, and
     * what {@link Fft#fft} would also use) with a {@code +i*omega*t}
     * temporal exponent, so that a rightward-propagating wave {@code
     * exp(i*(k0*x - omega0*t))} (omega0 &gt; 0) reports at {@code
     * +omega0}, not {@code -omega0}. {@link Fft#ifft} is exactly that
     * {@code +i} sign (its {@code 1/T} normalization is immaterial here -
     * a uniform scale factor cancels out of every power-fraction
     * comparison this class makes). Using {@link Fft#fft} for both axes
     * would compute the OTHER standard convention ({@code -i*(k*x +
     * omega*t)}) and silently report every propagating wave's frequency
     * with the wrong sign - caught by
     * {@code StructureFactorTest#planeWaveGivesSingleKOmegaPeak} during
     * development (it failed with {@code omega} negated before this
     * fix).
     */
    double[] powerSpectrumAt(double[][] fieldRe, double[][] fieldIm,
                              int mx, int my, int mz) {
        int t = fieldRe.length;
        double[] re = new double[t];
        double[] im = new double[t];
        for (int i = 0; i < t; i++) {
            double[] tmp = spatialDft(fieldRe[i],
                                       fieldIm == null ? null : fieldIm[i],
                                       mx, my, mz);
            re[i] = tmp[0];
            im[i] = tmp[1];
        }
        Fft.ifft(re, im);
        double[] power = new double[t];
        for (int p = 0; p < t; p++) {
            power[p] = re[p] * re[p] + im[p] * im[p];
        }
        return power;
    }

    /**
     * Ordinary-least-squares fit of {@code omega} against {@code k}
     * across {@code points} - a group-velocity estimate for the
     * dispersion branch those points trace out.
     */
    public Ridge extractRidge(List<DispersionPoint> points) {
        if (points == null || points.isEmpty()) {
            throw new IllegalArgumentException("points must be non-empty");
        }
        int n = points.size();
        double sumK = 0;
        double sumOmega = 0;
        for (DispersionPoint p : points) {
            sumK += p.k();
            sumOmega += p.omega();
        }
        double kMean = sumK / n;
        double omegaMean = sumOmega / n;
        double num = 0;
        double den = 0;
        for (DispersionPoint p : points) {
            double dk = p.k() - kMean;
            num += dk * (p.omega() - omegaMean);
            den += dk * dk;
        }
        double slope = den > 1e-12 ? num / den : 0.0;
        double intercept = omegaMean - slope * kMean;
        return new Ridge(points, slope, intercept);
    }

    /**
     * Direct DFT term at one 3-index grid point {@code (mx,my,mz)},
     * summed explicitly and ONLY over even-parity sites - see the class
     * javadoc's "Spatial transform" and reciprocal-lattice sections for
     * why this, rather than a zero-padded {@link Fft}, is what avoids
     * the ghost-image failure mode.
     */
    private double[] spatialDft(double[] fieldRe, double[] fieldIm, int mx,
                                 int my, int mz) {
        double kx = 2 * Math.PI * mx / extent.x;
        double ky = 2 * Math.PI * my / extent.y;
        double kz = 2 * Math.PI * mz / extent.z;
        double sumRe = 0;
        double sumIm = 0;
        for (int i = 0; i < extent.x; i++) {
            for (int j = 0; j < extent.y; j++) {
                for (int k = 0; k < extent.z; k++) {
                    if (((i + j + k) & 1) != 0) {
                        continue;
                    }
                    int idx = (i * extent.y + j) * extent.z + k;
                    double fr = fieldRe[idx];
                    double fi = fieldIm == null ? 0.0 : fieldIm[idx];
                    double theta = -(kx * i + ky * j + kz * k);
                    double c = Math.cos(theta);
                    double s = Math.sin(theta);
                    sumRe += fr * c - fi * s;
                    sumIm += fr * s + fi * c;
                }
            }
        }
        return new double[] { sumRe, sumIm };
    }

    private int axisExtentFor(Direction direction) {
        switch (direction) {
        case X100:
            return extent.x;
        case X110:
            if (extent.x != extent.y) {
                throw new IllegalArgumentException("X110 probe requires extent.x == extent.y, was "
                                                    + extent.x + " and "
                                                    + extent.y);
            }
            return extent.x;
        case X111:
            if (extent.x != extent.y || extent.y != extent.z) {
                throw new IllegalArgumentException("X111 probe requires extent.x == extent.y == extent.z, was "
                                                    + extent.x + ", "
                                                    + extent.y + ", "
                                                    + extent.z);
            }
            return extent.x;
        default:
            throw new IllegalArgumentException("unhandled direction: "
                                                + direction);
        }
    }

    private int[] kIndicesFor(Direction direction, int m) {
        switch (direction) {
        case X100:
            return new int[] { m, 0, 0 };
        case X110:
            return new int[] { m, m, 0 };
        case X111:
            return new int[] { m, m, m };
        default:
            throw new IllegalArgumentException("unhandled direction: "
                                                + direction);
        }
    }

    /**
     * The number of equal nonzero components the probe direction's
     * wavevector carries - 1 for X100, 2 for X110, 3 for X111 - i.e. the
     * factor {@code sqrt(Nd)} relates a single per-axis component to the
     * Euclidean magnitude {@code |k_vec|}, since all {@code Nd} nonzero
     * components share the same magnitude by construction
     * ({@link #kIndicesFor}).
     */
    private static int componentCountFor(Direction direction) {
        switch (direction) {
        case X100:
            return 1;
        case X110:
            return 2;
        case X111:
            return 3;
        default:
            throw new IllegalArgumentException("unhandled direction: "
                                                + direction);
        }
    }

    /**
     * {@code 2*pi*signed(m)/axisExtent} - a single per-axis
     * reciprocal-space component, SIGNED (folded, NOT {@code abs()}'d):
     * {@code m} beyond {@code axisExtent/2} is a negative-k alias
     * (matching {@code SpectrumAnalyzer#frequencyForBin}'s established
     * precedent) and must stay negative, not fold to a positive
     * magnitude.
     *
     * <p><b>Do not reintroduce {@code Math.abs()} here</b> (stacked
     * review round 2, critic, bead inviscid-0nx.9): a real-valued
     * field's spatial DFT is Hermitian ({@code F(-k,t) ==
     * conj(F(k,t))} for real {@code f}), so any real single-direction
     * propagating wave's mirror index ({@code axisExtent-m}) lands at
     * the exact negative of this component with the exact negative of
     * {@code omega} - i.e. exactly on the SAME {@code omega = c*k}
     * dispersion line. Folding this to a non-negative magnitude would
     * make that mirror collide with the forward point at an IDENTICAL
     * reported {@code k} but OPPOSITE-sign {@code omega}, which
     * CANCELS rather than reinforces in {@link #extractRidge}'s
     * unweighted OLS fit over the raw, unfiltered {@link #spectrum}
     * output - verified to silently corrupt the fit down to
     * ~66% of the true slope (not merely "some noise"), see
     * {@code StructureFactorTest#realFieldRidgeReinforcesAcrossMirrorPointsX100}.
     */
    private static double kComponentMagnitude(int m, int axisExtent) {
        return 2 * Math.PI * signedIndex(m, axisExtent) / axisExtent;
    }

    private void requireFieldShape(double[][] fieldRe, double[][] fieldIm) {
        if (fieldRe == null || fieldRe.length == 0) {
            throw new IllegalArgumentException("fieldByTick must be non-empty");
        }
        requirePowerOfTwo(fieldRe.length, "T (temporal series length)");
        int expected = extent.x * extent.y * extent.z;
        for (int t = 0; t < fieldRe.length; t++) {
            if (fieldRe[t] == null || fieldRe[t].length != expected) {
                throw new IllegalArgumentException("fieldByTick[" + t
                                                    + "] must have length "
                                                    + expected
                                                    + " (extent.x*extent.y*extent.z), was "
                                                    + (fieldRe[t] == null ? "null"
                                                                          : fieldRe[t].length));
            }
        }
        if (fieldIm != null) {
            if (fieldIm.length != fieldRe.length) {
                throw new IllegalArgumentException("fieldIm must have the same T as fieldRe: "
                                                    + fieldIm.length + " != "
                                                    + fieldRe.length);
            }
            for (int t = 0; t < fieldIm.length; t++) {
                if (fieldIm[t] == null || fieldIm[t].length != expected) {
                    throw new IllegalArgumentException("fieldIm[" + t
                                                        + "] must have length "
                                                        + expected);
                }
            }
        }
    }

    private static void requirePowerOfTwo(int n, String name) {
        if (n <= 0 || (n & (n - 1)) != 0) {
            throw new IllegalArgumentException(name
                                                + " must be a positive power of two, was "
                                                + n);
        }
    }

    /**
     * Bin {@code p} of a T-point temporal FFT, mapped to a signed
     * angular frequency (radians/tick) via {@link #signedIndex(int, int)}.
     */
    private static double signedOmega(int p, int t) {
        return 2 * Math.PI * signedIndex(p, t) / t;
    }

    /**
     * Index {@code idx} (in {@code [0, period)}) folded to a signed
     * representative in {@code (-period/2, period/2]}: {@code idx <=
     * period/2} stays positive, {@code idx > period/2} wraps negative -
     * the same upper-half-is-negative convention
     * {@code SpectrumAnalyzer#frequencyForBin} uses, shared here between
     * the temporal bin-to-omega mapping ({@link #signedOmega(int, int)})
     * and the spatial per-axis k-component mapping
     * ({@link #kComponentMagnitude(int, int)}).
     */
    private static int signedIndex(int idx, int period) {
        return idx > period / 2 ? idx - period : idx;
    }
}
